name: PrisonMines
version: '${project.version}'
main: com.github.gavvydizzle.prisonmines.PrisonMines
api-version: '1.20'
folia-supported: true
depend: [ ServerUtils, WorldEdit ]
softdepend: [ Multiverse-Core, PlaceholderAPI ]
authors: [ GavvyDizzle ]
description: Lightweight prison mines plugin for Spigot
commands:
  pmine:
    aliases: mines
    description: PrisonMines admin commands
    permission: prisonmines.mineadmin
    permission-message: Insufficient permission
  mine:
    description: Mine teleport command
